# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CSS-Tiny
version:      1.04
version_from: lib/CSS/Tiny.pm
installdirs:  site
requires:
    FindBin:                       0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.16
