name: CSS-Tiny
version: 1.09
abstract: Read/Write .css stylesheets with as little code as possible
author: Adam Kennedy<cpan@ali.as>
license: perl
distribution_type: module
build_requires:
  File::Spec: 0.82
  Test::More: 0.47
requires:
  perl: 5.005
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
